pub struct TDPStructure {}

#[cfg(test)]
mod tests {
    use crate::file::TDPName;

    #[test]
    pub fn test_deserialize() {
        let json = r#"{"league": {"league_major": "industrial", "league_minor": "logistics", "league_sub": null, "name": "industrial_logistics", "name_pretty": "Industrial Logistics"}, "team_name": {"name": "Carologistics", "name_pretty": "Carologistics"}, "year": 2019, "index": 0}"#;

        let txt = r#"{"paragraphs": [{"sequence_id": 0, "title": {"sequence_id": 0, "paragraph_id": 0, "raw": "1 Introduction", "processed": "introduction"}, "sentences": [{"sequence_id": 0, "paragraph_id": 0, "raw": "This paper is part of the qualification process to attend the RoboCup 2019 in Sydney Australia.", "processed": "paper part qualification process attend robocup 2019 sydney australia"}, {"sequence_id": 1, "paragraph_id": 0, "raw": "This paper is organized as follows.", "processed": "paper organized follows"}, {"sequence_id": 2, "paragraph_id": 0, "raw": "Section 2 provides the description of the Technical Institute of Applied Science HFTM.", "processed": "section provides description technical institute applied science hftm"}, {"sequence_id": 3, "paragraph_id": 0, "raw": "Section 3 presents the Didactic Concept.", "processed": "section present didactic concept"}, {"sequence_id": 4, "paragraph_id": 0, "raw": "Section 4 provides the description of the Team Solidus.", "processed": "section provides description team solidus"}, {"sequence_id": 5, "paragraph_id": 0, "raw": "Section 5 presents the history of the team.", "processed": "section present history team"}]}, {"sequence_id": 1, "title": {"sequence_id": 0, "paragraph_id": 1, "raw": "2 Technical Institute of Applied Science HFTM", "processed": "technical institute applied science hftm"}, "sentences": [{"sequence_id": 0, "paragraph_id": 1, "raw": "As a technical college, the HFT Midland offers education with practical relevance.", "processed": "technical college hft midland offer education practical relevance"}, {"sequence_id": 1, "paragraph_id": 1, "raw": "From the co-operation with the industry and a broadly supporting sponsorship emerges a constantly up-to-date outline of the profession of technicians in the subject areas of machinery construction and systems technology.", "processed": "co operation industry broadly supporting sponsorship emerges constantly date outline profession technician subject area machinery construction system technology"}, {"sequence_id": 2, "paragraph_id": 1, "raw": "In this way the close connection to the employment market is secured.", "processed": "way close connection employment market secured"}]"#;
    }
}
